name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, labeled, closed]
  pull_request_target:
    types: [opened, reopened, synchronize, labeled, closed]

jobs:
  tests:
    name: Heroku Review Application
    runs-on: ubuntu-latest
    steps:
      - name: Heroku Review Application
        uses: mheap/github-action-pr-heroku-review-app@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: behe/heroku-build@v1
        with:
          app-name: "obscure-plains-82299"
          api-key: "${{secrets.HEROKU_API_KEY}}"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "obscure-plains-82299" #Must be unique in Heroku
          heroku_email: "cfrancobedoya@gmail.com"
          usedocker: true
